version: "3.8"

services:
  # goapp:
  #   build: .
  #   container_name: goapp
  #   restart: always
  #   depends_on:
  #     - minio
  #     - mongo
  #   env_file:
  #     - .env
  #   ports:
  #     - "${APP_PORT}:8080"
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: ["./tmp/main"]

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web console
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data

  minio-mc:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}) do sleep 5; done &&
      /usr/bin/mc mb -p local/${MINIO_BUCKET} || true &&
      tail -f /dev/null
      "

volumes:
  minio-data:
  mongo_data:
